### ISSUE TITLE
为什么不做成多标签页的呢？现在很少单标签页的了吧。

### ISSUE THREAD

**Issue by wang2650** [colinin/vue-vben-admin-abp-vnext#1]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by colinin** [comment]
你都没有看过前端demo吧，这个可以设置多标签、多主题
